nouns = { "a":"Deus",
		"b":"Creator",
		"c":"Conditor",
		"d":"Opifex",
		"e":"Dominus",
		"f":"Dominator",
		"g":"Confolator",
		"h":"Arbiter",
		"i":"Iudex",
		"k":"Illuminator",
		"l":"Illustrator",
		"m":"Rector",
		"n":"Rex",
		"o":"Imperator",
		"p":"Gubernator",
		"q":"Factor",
		"r":"Fabricator",
		"s":"Conseruator",
		"t":"Redemptor",
		"v":"Auctor",
		"x":"Princeps",
		"y":"Pastor",
		"z":"Moderator" }

reverse_nouns = dict(reversed(item) for item in forward_map.items())

adjectives = { "a":"clemens",
		"b":"clementibimus",
		"c":"pius",
		"d":"pibimus",
		"e":"magnus",
		"f":"excelsus",
		"g":"maximus",
		"h":"optimus",
		"i":"sapientibimus",
		"k":"inuisibilis",
		"l":"immortalis",
		"m":"aeternus",
		"n":"semperiternus",
		"o":"gloriosus",
		"p":"fortisimus",
		"q":"sanctibimus",
		"r":"incompraehensibilis",
		"s":"omnipotens",
		"t":"pacificus",
		"v":"misericors",
		"x":"misericordibimus",
		"y":"cunctipotens",
		"z":"magnificus" }

reverse_adjectives = dict(reversed(item) for item in forward_map.items())
